version: "3.8"

services:
  shipment-api:
    build:
      context: .
      dockerfile: ShipmentSystem.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - shipment-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=shipment-db;Database=ShipmentDb;User=sa;Password=Your_password123;
    networks:
      - shipment-net

  shipment-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - shipment-net
    volumes:
      - shipmentdata:/var/opt/mssql

networks:
  shipment-net:

volumes:
  shipmentdata:
